# Generated by Django 4.1.3 on 2022-11-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=50, null=True)),
                ('iconUri', models.CharField(max_length=200)),
                ('manifestUri', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('movies', models.ManyToManyField(to='backed.movie')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
